"""Curated sensor/controller descriptions for the generated API stubs.

Source of truth for labels is the fork (AIGamePyLibrary DROPDOWN_OPTIONS);
the prose here is hand-written from game behavior + parity forensics. Keys
missing here fall back to the label itself — the generator never fails.
"""
from __future__ import annotations

TENNIS_BOOL = {
    "Is Playing": "True while the match simulation runs (not menus).",
    "Is Home": "True when this brain plays the home side.",
    "Is Self Server For Set": "True when self serves this set.",
    "Is Opponent Server For Set": "True when the opponent serves this set.",
    "Is Serve Phase": "True while the ball is dead and the server prepares.",
    "Is Self Actively Serving": "True when self is the current server.",
    "Is Second Serve": "True when the upcoming serve is the second (after a fault).",
    "Is Ad Court Serve": "True when serving from the ad (left) side.",
    "Is Ball Playable": "True when the ball is live and can be struck.",
    "Was Last Shot Topspin": "True when the last struck shot was topspin.",
    "Was Last Shot Slice": "True when the last struck shot was slice.",
    "Was Last Shot Flat": "True when the last struck shot was flat.",
    "Was Last Shot Lob": "True when the last struck shot was a lob.",
    "Was Last Shot Drop": "True when the last struck shot was a drop shot.",
    "Was Last Shot Curve Left": "True when the last shot curved left.",
    "Was Last Shot Curve Right": "True when the last shot curved right.",
    "Was Last Shot Trick": "True when the last shot was a trick shot.",
    "Is Self Charging": "True while self holds swing (charge 0.17-1.0).",
    "Is Opponent Charging": "True while the opponent holds swing.",
    "Is Self Winning": "True when self leads the score.",
    "Is Opponent Winning": "True when the opponent leads the score.",
    "Is Tied": "True when the score is level.",
    "Is Deuce": "True at deuce (3+ points each, no advantage).",
    "Is Game Point": "True when the next point wins the game for either side.",
    "Is Break Point": "True when the receiver can break serve next point.",
    "Is Match Point": "True when the next point wins the match for either side.",
    "Ball On Self Side": "True when the ball is over your half.",
    "Ball Incoming": "True only while the opponent's shot travels un-bounced toward you; goes false at the first bounce.",
    "Ball In Swing Range": "True when the ball is within strike radius.",
    "Ball Has Bounced": "True once the ball bounced since the last strike.",
    "Must Wait For Bounce": "True when the receiver must let the serve bounce first.",
    "Ball Has Charged Effect": "True when a charged-shot effect rides the ball.",
    "Self Scored Last Point": "True when you won the previous point.",
    "Opponent Scored Last Point": "True when the opponent won the previous point.",
    "Self Has Advantage": "True when you hold advantage at deuce.",
}

TENNIS_FLOAT = {
    "Shot: Topspin": "Constant id of the topspin shot (feed to move shot).",
    "Shot: Slice": "Constant id of the slice shot.",
    "Shot: Flat": "Constant id of the flat shot.",
    "Shot: Drop": "Constant id of the drop shot.",
    "Shot: Lob": "Constant id of the lob shot.",
    "Shot: Curve Left": "Constant id of the curve-left shot.",
    "Shot: Curve Right": "Constant id of the curve-right shot.",
    "Shot: Random": "Constant id asking the game to pick a shot.",
    "Shot: Last Self Shot": "Id of your most recent shot.",
    "Shot: Last Opponent Shot": "Id of the opponent's most recent shot.",
    "Shot: Most Used Self Shot": "Id of your most frequent shot.",
    "Shot: Most Used Opponent Shot": "Id of the opponent's most frequent shot.",
    "Shot: Most Scored Self Shot": "Id of the shot you scored most with.",
    "Shot: Most Scored Opponent Shot": "Id of the shot the opponent scored most with.",
    "Shot: Ball": "Id of the shot currently in flight.",
    "Self Swing Charge Pct": "Your swing charge 0-1 (hold builds it).",
    "Opponent Swing Charge Pct": "Opponent swing charge 0-1.",
    "Self Stamina Pct": "Your stamina 0-1 (sprint drains it).",
    "Opponent Stamina Pct": "Opponent stamina 0-1.",
    "Deuce Fatigue": "Fatigue factor active at deuce.",
    "Rally Fatigue": "Fatigue factor growing with rally length.",
    "Court Width": "Playable court width (singles).",
    "Court Depth": "Playable court length (baseline to baseline).",
    "Net Height": "Net tape height.",
    "Ball Speed": "Current ball speed.",
    "Ball Time To Ground": "Predicted seconds until the ball lands.",
    "Ball Time To 2nd Bounce": "Predicted seconds until the second bounce.",
    "Self Time To Destination": "Seconds for you to reach your move target.",
    "Serve Number": "1 for first serve, 2 for second serve.",
    "Self Points": "Your points in the current game.",
    "Opponent Points": "Opponent points in the current game.",
    "Self Set Score": "Sets (matches) you have won.",
    "Opponent Set Score": "Sets the opponent has won.",
    "Self Aces": "Your ace count.",
    "Opponent Aces": "Opponent ace count.",
    "Self Faults": "Your serve-fault count.",
    "Opponent Faults": "Opponent serve-fault count.",
    "Self Double Faults": "Your double-fault count.",
    "Opponent Double Faults": "Opponent double-fault count.",
    "Self Fouls": "Your foul count.",
    "Opponent Fouls": "Opponent foul count.",
    "Self Outs": "Your out count.",
    "Opponent Outs": "Opponent out count.",
    "Self Charged Shots": "Your fully-charged shot count.",
    "Opponent Charged Shots": "Opponent fully-charged shot count.",
    "Current Simulation Time": "Match clock in seconds.",
    "Sim Tick": "Current simulation tick.",
    "Delta Time": "Frame delta in seconds.",
    "Fixed Delta Time": "Physics tick delta in seconds.",
}

TENNIS_VECTOR3 = {
    "Ball Position": "Ball court position (x, z).",
    "Ball Velocity": "Ball velocity vector.",
    "Predicted Bounce": "Where the ball will land first.",
    "Predicted 2nd Bounce": "Where the ball will land second.",
    "Center Of Half": "Middle of your half (safe rally target).",
    "Center Of Back": "Middle of your back court.",
    "Serve Stance": "Where the server must stand (inside the serve area).",
    "Receive Stance": "Where the receiver should wait.",
    "Legal Serve Target": "Center of the legal diagonal serve box.",
    "Random Aim Target": "A game-picked aim point.",
    "Self Average Scoring Location": "Where your winners usually land.",
    "Opponent Average Scoring Location": "Where their winners usually land.",
    "Estimated Opponent Shot Location": "Game's guess at their landing spot.",
    "Trick Drop Modifier": "Aim offset making a trick shot drop.",
    "Trick Lob Modifier": "Aim offset making a trick shot lob.",
    "Trick Curve Left Modifier": "Aim offset curving a trick shot left.",
    "Trick Curve Right Modifier": "Aim offset curving a trick shot right.",
    "Camera Forward": "Camera facing direction.",
    "Camera Right": "Camera right direction.",
}

TENNIS_TRANSFORM = {
    "Self": "Your position.",
    "Opponent": "Opponent position.",
    "Self Racket Center": "Your racket head position (strike point).",
    "Ball": "Ball position.",
    "Camera": "Camera position.",
}

SOCCER_BOOL = {
    "Team Has Ball": "True when a teammate (or you) holds the ball.",
    "Opponent Has Ball": "True when an opponent holds the ball.",
    "Is Ball Loose": "True when nobody holds the ball.",
    "Team Player 1 Has Ball": "True when team player 1 holds the ball.",
    "Team Player 2 Has Ball": "True when team player 2 holds the ball.",
    "Team Player 3 Has Ball": "True when team player 3 holds the ball.",
    "Team Player 4 Has Ball": "True when team player 4 holds the ball.",
    "Opponent Player 1 Has Ball": "True when opponent 1 holds the ball.",
    "Opponent Player 2 Has Ball": "True when opponent 2 holds the ball.",
    "Opponent Player 3 Has Ball": "True when opponent 3 holds the ball.",
    "Opponent Player 4 Has Ball": "True when opponent 4 holds the ball.",
    "Is Ball Nearby Team Player 1": "True when the ball is near team player 1.",
    "Is Ball Nearby Team Player 2": "True when the ball is near team player 2.",
    "Is Ball Nearby Team Player 3": "True when the ball is near team player 3.",
    "Is Ball Nearby Team Player 4": "True when the ball is near team player 4.",
    "Is Ball Nearby Opponent Player 1": "True when the ball is near opponent 1.",
    "Is Ball Nearby Opponent Player 2": "True when the ball is near opponent 2.",
    "Is Ball Nearby Opponent Player 3": "True when the ball is near opponent 3.",
    "Is Ball Nearby Opponent Player 4": "True when the ball is near opponent 4.",
    "Is Team Player 1 Closest Teammate to Ball": "True when team player 1 is the closest teammate to the ball.",
    "Is Team Player 2 Closest Teammate to Ball": "True when team player 2 is the closest teammate to the ball.",
    "Is Team Player 3 Closest Teammate to Ball": "True when team player 3 is the closest teammate to the ball.",
    "Is Team Player 4 Closest Teammate to Ball": "True when team player 4 is the closest teammate to the ball.",
    "Is Opponent Player 1 Closest Opponent to Ball": "True when opponent 1 is the closest opponent to the ball.",
    "Is Opponent Player 2 Closest Opponent to Ball": "True when opponent 2 is the closest opponent to the ball.",
    "Is Opponent Player 3 Closest Opponent to Ball": "True when opponent 3 is the closest opponent to the ball.",
    "Is Opponent Player 4 Closest Opponent to Ball": "True when opponent 4 is the closest opponent to the ball.",
    "Is Team Player 1 Open": "True when team player 1 has no close marker.",
    "Is Team Player 2 Open": "True when team player 2 has no close marker.",
    "Is Team Player 3 Open": "True when team player 3 has no close marker.",
    "Is Team Player 4 Open": "True when team player 4 has no close marker.",
    "Is Opponent Player 1 Open": "True when opponent 1 has no close marker.",
    "Is Opponent Player 2 Open": "True when opponent 2 has no close marker.",
    "Is Opponent Player 3 Open": "True when opponent 3 has no close marker.",
    "Is Opponent Player 4 Open": "True when opponent 4 has no close marker.",
    "Is Kickoff": "True during kickoff setup.",
    "Is Team Kicking off": "True when your team kicks off.",
    "Is Opponent Kicking off": "True when the opponent kicks off.",
    "Team Is Winning": "True when your team leads.",
    "Opponent Is Winning": "True when the opponent leads.",
    "Team Scored Last Point": "True when your team scored last.",
    "Opponent Scored Last Point": "True when the opponent scored last.",
    "Ball On Team Side": "True when the ball is on your half.",
    "Ball On Opponent Side": "True when the ball is on their half.",
    "Is Ball Headed Towards Team Goal": "True when ball velocity aims at your goal.",
    "Is Ball Headed Towards Opponent Goal": "True when ball velocity aims at their goal.",
    "Is Home Team": "True when this brain plays the home team.",
    "Is Away Team": "True when this brain plays the away team.",
    "Is Active Graph": "True when this graph is the one driving the player.",
}

SOCCER_FLOAT = {
    "Team Score": "Your team goals.",
    "Opponent Score": "Opponent goals.",
    "Team Shots": "Your team shot count.",
    "Opponent Shots": "Opponent shot count.",
    "Team Possession %": "Your possession share 0-1.",
    "Opponent Possession %": "Opponent possession share 0-1.",
    "Team Attacking %": "Share of your play in attack 0-1.",
    "Opponent Attacking %": "Share of opponent play in attack 0-1.",
    "Ball Speed": "Current ball speed.",
    "Player Interact Radius": "How close a player must be to touch the ball.",
    "Ball Carrier Stamina": "Stamina of whoever holds the ball.",
    "Ball Carrier Shot Charge": "Shot charge of whoever holds the ball.",
    "Teammate 1 Shot Charge": "Shot charge of teammate 1.",
    "Teammate 2 Shot Charge": "Shot charge of teammate 2.",
    "Teammate 3 Shot Charge": "Shot charge of teammate 3.",
    "Teammate 4 Shot Charge": "Shot charge of teammate 4.",
    "Field Width": "Playable field width.",
    "Field Depth": "Playable field length.",
    "Kickoff Circle Radius": "Center circle radius.",
    "Goal Width": "Goal mouth width.",
    "Goal Height": "Goal height.",
    "Team Player 1 Stamina": "Stamina of team player 1.",
    "Team Player 2 Stamina": "Stamina of team player 2.",
    "Team Player 3 Stamina": "Stamina of team player 3.",
    "Team Player 4 Stamina": "Stamina of team player 4.",
    "Distance from Team Player 1 to nearest Opponent": "How much space team player 1 has.",
    "Distance from Team Player 2 to nearest Opponent": "How much space team player 2 has.",
    "Distance from Team Player 3 to nearest Opponent": "How much space team player 3 has.",
    "Distance from Team Player 4 to nearest Opponent": "How much space team player 4 has.",
    "Opponent Player 1 Stamina": "Stamina of opponent 1.",
    "Opponent Player 2 Stamina": "Stamina of opponent 2.",
    "Opponent Player 3 Stamina": "Stamina of opponent 3.",
    "Opponent Player 4 Stamina": "Stamina of opponent 4.",
    "Opponent Nearest Teammate Player 1 Stamina": "Stamina of the opponent nearest your player 1.",
    "Opponent Nearest Teammate Player 2 Stamina": "Stamina of the opponent nearest your player 2.",
    "Opponent Nearest Teammate Player 3 Stamina": "Stamina of the opponent nearest your player 3.",
    "Opponent Nearest Teammate Player 4 Stamina": "Stamina of the opponent nearest your player 4.",
    "Stamina of last defending opponent": "Stamina of the last defender.",
    "Current Simulation Time": "Match clock in seconds.",
    "Max Simulation Time": "Match length in seconds.",
    "Simulation Time Remaining": "Seconds left on the clock.",
    "Delta Time": "Frame delta in seconds.",
    "Fixed Delta Time": "Physics tick delta in seconds.",
    "Pi": "3.14159.",
}

SOCCER_VECTOR3 = {
    "Ball Velocity": "Ball velocity vector.",
    "Clear direction from team carrier": "Safe clear direction for the carrier.",
    "Backwards clear direction from team carrier": "Clear backwards for the carrier.",
    "Clear direction from team carrier (avoid goal lines)": "Clear that stays in play past the lines.",
    "Clear direction from team carrier (avoid sidelines)": "Clear that stays in past the sidelines.",
    "Clear direction from team carrier (avoid all walls)": "Clear that stays in play.",
    "Upper Corner Home Side": "Corner position, home side upper.",
    "Lower Corner Home Side": "Corner position, home side lower.",
    "Upper Midfield": "Midfield position, upper.",
    "Lower Midfield": "Midfield position, lower.",
    "Upper Corner Away Side": "Corner position, away side upper.",
    "Lower Corner Away Side": "Corner position, away side lower.",
    "Upper Corner Opposing Side": "Opposing corner, upper.",
    "Lower Corner Opposing Side": "Opposing corner, lower.",
    "Upper Corner Team Side": "Team corner, upper.",
    "Lower Corner Team Side": "Team corner, lower.",
    "Center Field": "Center spot.",
    "Get nearest open teammate": "Position of the nearest open teammate.",
    "Get furthest open teammate": "Position of the furthest open teammate.",
    "Get most open teammate": "Position of the most open teammate.",
    "Get nearest open opponent": "Position of the nearest open opponent.",
    "Get furthest open opponent": "Position of the furthest open opponent.",
    "Get most open opponent": "Position of the most open opponent.",
    "Direction of clear teammate from Teammate 1": "Where teammate 1 should clear to find a teammate.",
    "Direction of clear teammate from Teammate 2": "Where teammate 2 should clear to find a teammate.",
    "Direction of clear teammate from Teammate 3": "Where teammate 3 should clear to find a teammate.",
    "Direction of clear teammate from Teammate 4": "Where teammate 4 should clear to find a teammate.",
    "Direction of clear teammate from Opponent 1": "Where opponent 1 would clear to find a teammate.",
    "Direction of clear teammate from Opponent 2": "Where opponent 2 would clear to find a teammate.",
    "Direction of clear teammate from Opponent 3": "Where opponent 3 would clear to find a teammate.",
    "Direction of clear teammate from Opponent 4": "Where opponent 4 would clear to find a teammate.",
    "Direction of ball from Teammate 1": "Ball direction seen from teammate 1.",
    "Direction of ball from Teammate 2": "Ball direction seen from teammate 2.",
    "Direction of ball from Teammate 3": "Ball direction seen from teammate 3.",
    "Direction of ball from Teammate 4": "Ball direction seen from teammate 4.",
    "Direction of ball from Opponent 1": "Ball direction seen from opponent 1.",
    "Direction of ball from Opponent 2": "Ball direction seen from opponent 2.",
    "Direction of ball from Opponent 3": "Ball direction seen from opponent 3.",
    "Direction of ball from Opponent 4": "Ball direction seen from opponent 4.",
    "Direction of team goal from Teammate 1": "Own-goal direction from teammate 1.",
    "Direction of team goal from Teammate 2": "Own-goal direction from teammate 2.",
    "Direction of team goal from Teammate 3": "Own-goal direction from teammate 3.",
    "Direction of team goal from Teammate 4": "Own-goal direction from teammate 4.",
    "Direction of opponent goal from Teammate 1": "Their-goal direction from teammate 1.",
    "Direction of opponent goal from Teammate 2": "Their-goal direction from teammate 2.",
    "Direction of opponent goal from Teammate 3": "Their-goal direction from teammate 3.",
    "Direction of opponent goal from Teammate 4": "Their-goal direction from teammate 4.",
    "Clear direction from Teammate 1": "Safe clear direction for teammate 1.",
    "Clear direction from Teammate 2": "Safe clear direction for teammate 2.",
    "Clear direction from Teammate 3": "Safe clear direction for teammate 3.",
    "Clear direction from Teammate 4": "Safe clear direction for teammate 4.",
    "Direction of teammate from Team Player 1": "Pass direction from team player 1.",
    "Direction of teammate from Team Player 2": "Pass direction from team player 2.",
    "Direction of teammate from Team Player 3": "Pass direction from team player 3.",
    "Direction of teammate from Team Player 4": "Pass direction from team player 4.",
}

SOCCER_TRANSFORM = {
    "Ball": "Ball position.",
    "Team Player 1": "Position of team player 1.",
    "Team Player 2": "Position of team player 2.",
    "Team Player 3": "Position of team player 3.",
    "Team Player 4": "Position of team player 4.",
    "Opponent Player 1": "Position of opponent 1.",
    "Opponent Player 2": "Position of opponent 2.",
    "Opponent Player 3": "Position of opponent 3.",
    "Opponent Player 4": "Position of opponent 4.",
    "Teammate Nearest Team Player 1": "Teammate closest to your player 1.",
    "Teammate Nearest Team Player 2": "Teammate closest to your player 2.",
    "Teammate Nearest Team Player 3": "Teammate closest to your player 3.",
    "Teammate Nearest Team Player 4": "Teammate closest to your player 4.",
    "Opponent Nearest Team Player 1": "Opponent closest to your player 1.",
    "Opponent Nearest Team Player 2": "Opponent closest to your player 2.",
    "Opponent Nearest Team Player 3": "Opponent closest to your player 3.",
    "Opponent Nearest Team Player 4": "Opponent closest to your player 4.",
    "Team Goal Center": "Middle of your goal.",
    "Team Goal Left Post": "Your left post.",
    "Team Goal Right Post": "Your right post.",
    "Opponent Goal Center": "Middle of their goal.",
    "Opponent Goal Left Post": "Their left post.",
    "Opponent Goal Right Post": "Their right post.",
    "Opponent Nearest Team Goal": "Opponent closest to your goal.",
    "Opponent Nearest Opponent Goal": "Opponent closest to their goal.",
    "Teammate Nearest Team Goal": "Teammate closest to your goal.",
    "Teammate Nearest Opponent Goal": "Teammate closest to their goal.",
}

TENNIS_MOVE_DOC = (
    "Drive to court position (x, z) and strike: swing truthy charges/hits, "
    "shot is a Shot:* id, sprint truthy sprints. Exactly one controller "
    "call per tick."
)
TENNIS_MOVE_VEC_DOC = (
    "Same as move but driven by a vector (vec_make or a vector sensor)."
)
SOCCER_MOVE_DOC = (
    "Drive to field position (x, z). Exactly one controller call per tick."
)

BY_GAME = {
    ("tennis", "bool"): TENNIS_BOOL,
    ("tennis", "float"): TENNIS_FLOAT,
    ("tennis", "vector3"): TENNIS_VECTOR3,
    ("tennis", "transform"): TENNIS_TRANSFORM,
    ("soccer", "bool"): SOCCER_BOOL,
    ("soccer", "float"): SOCCER_FLOAT,
    ("soccer", "vector3"): SOCCER_VECTOR3,
    ("soccer", "transform"): SOCCER_TRANSFORM,
}


def describe(game: str, kind: str, label: str) -> str:
    """One-line doc for a sensor; falls back to the label itself."""
    return BY_GAME.get((game, kind), {}).get(label, label)
